apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: mybackend
  replicas: 2
  template:
    metadata:
      labels:
        app: mybackend
    spec:
      containers:
      - name: test
        image: registry.lan/backend:1.0.0
        ports:
        - containerPort: 8080
