apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: myfrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: myfrontend
    spec:
      containers:
      - name: test
        image: registry.lan/frontend:1.0.0
        ports:
        - containerPort: 8080
        env:
          - name: BACKEND
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: backend
